-- -- • Calculate the total number of orders for each respective month.
-- -- • Determine the month-on-month increase or decrease in the number of orders.
-- -- • Calculate the difference in the number of orders between the selected month and the previous 